"""Baseline: full schema generated from current models.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-09-24 21:37:44.249802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('account_clusters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cluster_type', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('discovery_method', sa.String(length=20), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('toxicity_score', sa.Float(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_clusters_id'), 'account_clusters', ['id'], unique=False)
    op.create_index(op.f('ix_account_clusters_owner_id'), 'account_clusters', ['owner_id'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_used', sa.String(length=20), nullable=False),
    sa.Column('tool_input', sa.JSON(), nullable=True),
    sa.Column('tool_output', sa.JSON(), nullable=True),
    sa.Column('response_model', sa.String(length=50), nullable=True),
    sa.Column('response_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_id'), 'ai_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_session_id'), 'ai_conversations', ['session_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'USED', 'REVOKED', 'EXPIRED', name='tokenstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_rotated', sa.Boolean(), nullable=False),
    sa.Column('replaced_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_created_at'), 'refresh_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('cluster_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cluster_a_id', sa.String(length=36), nullable=False),
    sa.Column('cluster_b_id', sa.String(length=36), nullable=False),
    sa.Column('connection_type', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_a_id'], ['account_clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cluster_b_id'], ['account_clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cluster_connections_cluster_a_id'), 'cluster_connections', ['cluster_a_id'], unique=False)
    op.create_index(op.f('ix_cluster_connections_cluster_b_id'), 'cluster_connections', ['cluster_b_id'], unique=False)
    op.create_index(op.f('ix_cluster_connections_created_by_id'), 'cluster_connections', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_cluster_connections_id'), 'cluster_connections', ['id'], unique=False)
    op.create_table('external_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('platform_user_id', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['account_clusters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_accounts_cluster_id'), 'external_accounts', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_external_accounts_id'), 'external_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_external_accounts_platform'), 'external_accounts', ['platform'], unique=False)
    op.create_index(op.f('ix_external_accounts_platform_user_id'), 'external_accounts', ['platform_user_id'], unique=False)
    op.create_index(op.f('ix_external_accounts_username'), 'external_accounts', ['username'], unique=False)
    op.create_table('comments',
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('original_author', sa.String(length=255), nullable=True),
    sa.Column('original_author_id', sa.String(length=255), nullable=True),
    sa.Column('original_author_url', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_platform', sa.String(length=50), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('external_account_id', sa.String(length=36), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('platform_comment_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'WAITING', name='commentstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='commentpriority'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('vote_score', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['external_account_id'], ['external_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_created_at'), 'comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_comments_external_account_id'), 'comments', ['external_account_id'], unique=False)
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_platform'), 'comments', ['platform'], unique=False)
    op.create_index(op.f('ix_comments_platform_comment_id'), 'comments', ['platform_comment_id'], unique=False)
    op.create_index(op.f('ix_comments_status'), 'comments', ['status'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_table('classifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('backend', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('harmful_score', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classifications_backend'), 'classifications', ['backend'], unique=False)
    op.create_index(op.f('ix_classifications_category'), 'classifications', ['category'], unique=False)
    op.create_index(op.f('ix_classifications_comment_id'), 'classifications', ['comment_id'], unique=False)
    op.create_index(op.f('ix_classifications_id'), 'classifications', ['id'], unique=False)
    op.create_index(op.f('ix_classifications_severity'), 'classifications', ['severity'], unique=False)
    op.create_table('comment_embeddings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_embeddings_comment_id'), 'comment_embeddings', ['comment_id'], unique=True)
    op.create_index(op.f('ix_comment_embeddings_id'), 'comment_embeddings', ['id'], unique=False)
    op.create_table('comment_mentions',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('external_account_id', sa.String(length=36), nullable=False),
    sa.Column('mentioned_username', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['external_account_id'], ['external_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'external_account_id', name='uq_comment_mention')
    )
    op.create_index(op.f('ix_comment_mentions_comment_id'), 'comment_mentions', ['comment_id'], unique=False)
    op.create_index(op.f('ix_comment_mentions_created_at'), 'comment_mentions', ['created_at'], unique=False)
    op.create_index(op.f('ix_comment_mentions_external_account_id'), 'comment_mentions', ['external_account_id'], unique=False)
    op.create_index(op.f('ix_comment_mentions_id'), 'comment_mentions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_mentions_id'), table_name='comment_mentions')
    op.drop_index(op.f('ix_comment_mentions_external_account_id'), table_name='comment_mentions')
    op.drop_index(op.f('ix_comment_mentions_created_at'), table_name='comment_mentions')
    op.drop_index(op.f('ix_comment_mentions_comment_id'), table_name='comment_mentions')
    op.drop_table('comment_mentions')
    op.drop_index(op.f('ix_comment_embeddings_id'), table_name='comment_embeddings')
    op.drop_index(op.f('ix_comment_embeddings_comment_id'), table_name='comment_embeddings')
    op.drop_table('comment_embeddings')
    op.drop_index(op.f('ix_classifications_severity'), table_name='classifications')
    op.drop_index(op.f('ix_classifications_id'), table_name='classifications')
    op.drop_index(op.f('ix_classifications_comment_id'), table_name='classifications')
    op.drop_index(op.f('ix_classifications_category'), table_name='classifications')
    op.drop_index(op.f('ix_classifications_backend'), table_name='classifications')
    op.drop_table('classifications')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_status'), table_name='comments')
    op.drop_index(op.f('ix_comments_platform_comment_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_platform'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_external_account_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_created_at'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_external_accounts_username'), table_name='external_accounts')
    op.drop_index(op.f('ix_external_accounts_platform_user_id'), table_name='external_accounts')
    op.drop_index(op.f('ix_external_accounts_platform'), table_name='external_accounts')
    op.drop_index(op.f('ix_external_accounts_id'), table_name='external_accounts')
    op.drop_index(op.f('ix_external_accounts_cluster_id'), table_name='external_accounts')
    op.drop_table('external_accounts')
    op.drop_index(op.f('ix_cluster_connections_id'), table_name='cluster_connections')
    op.drop_index(op.f('ix_cluster_connections_created_by_id'), table_name='cluster_connections')
    op.drop_index(op.f('ix_cluster_connections_cluster_b_id'), table_name='cluster_connections')
    op.drop_index(op.f('ix_cluster_connections_cluster_a_id'), table_name='cluster_connections')
    op.drop_table('cluster_connections')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_created_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_session_id'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_account_clusters_owner_id'), table_name='account_clusters')
    op.drop_index(op.f('ix_account_clusters_id'), table_name='account_clusters')
    op.drop_table('account_clusters')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
